export const GOOD_INFO = 'GOOD_INFO'
export const SET_SIZE = 'SET_SIZE'
export const COMMODITY_LIST = 'COMMODITY_LIST'
export const GOODPHOTO = 'GOODPHOTO'
export const GODOWNID = 'GODOWNID'
export const GOODSHAREINFO = 'GOODSHAREINFO'
export const HELPID = 'HELPID'
export const ADDRESSID = 'ADDRESSID'
export const COMMODITY = 'COMMODITY'
export const SET_ORDER_STATE = 'SET_ORDER_STATE'
export const SET_ORDER_INDEX = 'SET_ORDER_INDEX'
// SET_ORDER_INFO order-list
export const SET_ORDER_INFO = 'SET_ORDER_INFO'
export const RECRUITSCROLLY = 'RECRUITSCROLLY'
export const MOD_INDEX = 'MOD_INDEX'
export const MY_INDEX = 'MY_INDEX'
export const SUBMIT_ID = 'SUBMIT_ID'
export const CURRENT_ID = 'CURRENT_ID'
// export const COMPANY = 'COMPANY'
export const CATEGORY = 'CATEGORY'
export const CATEGORY_ID = 'CATEGORY_ID'
export const BRANDSHOW = 'BRANDSHOW'
export const BRANDSKU = 'BRANDSKU'
export const GOODSSKU = 'GOODSSKU'
export const CHOOSEBRAND = 'CHOOSEBRAND'
export const SKUSHOW = 'SKUSHOW'
export const SET_EDIT_CATEGORY = 'SET_EDIT_CATEGORY'
export const SKUARR = 'SKUARR'
// edit-goods
export const MODEDATA = 'MODEDATA'
export const CLEARMODEDATA = 'CLEARMODEDATA'
export const ADDALLIANCE = 'ADDALLIANCE'
export const ADDALLIANCENAME = 'ADDALLIANCENAME'
// 保存以及清空联盟活动
export const SAVAACTIVITY = 'SAVAACTIVITY'
export const MODIFYTABNUMBER = 'MODIFYTABNUMBER'
// 商圈联盟统计下拉数据
export const SETALLIANCESTATISTICSDATALIST = 'SETALLIANCESTATISTICSDATALIST'
