export const SET_LIST_INFO = 'SET_LIST_INFO'
export const UPDATE_QUOTATION = 'UPDATE_QUOTATION'
export const SET_AUTHEN_ROLE = 'SET_AUTHEN_ROLE'
export const SET_RECGOODS = 'SET_RECGOODS'
export const SET_COMMENT_TEXT = 'SET_COMMENT_TEXT'
export const SET_SHOP_LIST = 'SET_SHOP_LIST'
// 消息相关 --- 是否修改消息红点展示状态
export const MODIFYMESSAGESTATUS = 'MODIFYMESSAGESTATUS'
// 联盟活动统计下拉数据
export const SETALLIANCESTATISTICSDATALIST = 'SETALLIANCESTATISTICSDATALIST'
